[package]
name = "gravity"
version = "0.1.0"
authors = ["pmosakowski <pmosakowski@users.noreply.github.com>"]

[dependencies]
conrod = { version = "*", features = ["glium"] }
glium = "*"
find_folder = "*"
